---
name: Upload release to Galaxy

on:
  release:
    types: [released]
env:
  PYTHON_VERSION: '3.11'
jobs:
  version:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      from_file: ${{ steps.yaml-data.outputs.data }}
    steps:
    - uses: actions/checkout@v4
    - name: Run read-yaml action
      id: yaml-data
      uses: jbutcher5/read-yaml@1.6
      with:
        file: './galaxy.yml'
        key-path: '["version"]'
    - name: Error if version mismatch
      run: echo "::error ::Version mismatch"
      if: format('v{0}', steps.yaml-data.outputs.data) != github.event.release.tag_name
  deploy:
    needs: version
    if: format('v{0}', needs.version.outputs.from_file) == github.event.release.tag_name
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install ansible and tests
      run: pip install -r requirements-test.txt
    - name: Build and publish
      env:
        ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
      run: |
        ansible-galaxy collection build .
        ansible-galaxy collection publish *.tar.gz --token $ANSIBLE_GALAXY_TOKEN
